import sqlite3
connection = sqlite3.connect("test.db")
cursor = connection.cursor()

cursor.execute("INSERT INTO tblCustomers VALUES(1, 'Chet Edwardson', '8795843078')")
cursor.execute("INSERT INTO tblCustomers VALUES(2, 'Hugh G. Rection', '2195545797')")
cursor.execute("INSERT INTO tblCustomers VALUES(3, '_xXQuickSc0p3rXx_', '9012390671')")
cursor.execute("INSERT INTO tblCustomers VALUES(4, 'Tikhon Fyodorov', '8458322314')")
cursor.execute("INSERT INTO tblCustomers VALUES(5, 'Ippolit Medved', '6753683774')")
cursor.execute("INSERT INTO tblCustomers VALUES(6, 'Sophie Wain', '5749257688')")
cursor.execute("INSERT INTO tblCustomers VALUES(7, 'Rufina Pavlov', '8768511860')")
cursor.execute("INSERT INTO tblCustomers VALUES(8, 'Stas Vinogradov', '8828762254')")
cursor.execute("INSERT INTO tblCustomers VALUES(9, 'Sashok Lebedev', '2848685135')")
cursor.execute("INSERT INTO tblCustomers VALUES(10, 'Irina Krupin', '3058131806')")

cursor.execute("INSERT INTO tblDogs VALUES(1, 'Kepheus', 65, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(2, 'Androcles', 10, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(3, 'Philomele', 5, 'Female')")
cursor.execute("INSERT INTO tblDogs VALUES(4, 'Project Pyke', 78, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(5, 'Theophanes', 71, 'Female')")
cursor.execute("INSERT INTO tblDogs VALUES(6, 'Eudoxia', 62, 'Female')")
cursor.execute("INSERT INTO tblDogs VALUES(7, 'Platon', 14, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(8, 'Alexios', 40, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(9, 'Abyss', 26, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(10, 'Proteus', 36, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(11, 'Solon', 76, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(12, 'Dardanos', 41, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(13, 'Zosime', 11, 'Male')")
cursor.execute("INSERT INTO tblDogs VALUES(14, 'Medeia', 6, 'Female')")
cursor.execute("INSERT INTO tblDogs VALUES(15, 'Punani Pablo', 15, 'Male')")

cursor.execute("INSERT INTO custDogs VALUES(1,1)")
cursor.execute("INSERT INTO custDogs VALUES(7,2)")
cursor.execute("INSERT INTO custDogs VALUES(4,3)")
cursor.execute("INSERT INTO custDogs VALUES(5,4)")
cursor.execute("INSERT INTO custDogs VALUES(9,5)")
cursor.execute("INSERT INTO custDogs VALUES(10,6)")
cursor.execute("INSERT INTO custDogs VALUES(3,7)")
cursor.execute("INSERT INTO custDogs VALUES(6,8)")
cursor.execute("INSERT INTO custDogs VALUES(5,9)")
cursor.execute("INSERT INTO custDogs VALUES(10,10)")
cursor.execute("INSERT INTO custDogs VALUES(8,11)")
cursor.execute("INSERT INTO custDogs VALUES(4,12)")
cursor.execute("INSERT INTO custDogs VALUES(8,13)")
cursor.execute("INSERT INTO custDogs VALUES(9,14)")
cursor.execute("INSERT INTO custDogs VALUES(2,15)")

connection.commit()
connection.close()
